name: Publish Docker Image

on: 
  push: 
    branches: main
  pull_request:
    branches: main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Build and Push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: yuriizd/g2d-hubhub
          registry: docker.io
#          tags: latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
#

          








      
